# Generated by Django 2.1.4 on 2019-01-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='role',
            new_name='roles',
        ),
    ]
