# Generated by Django 2.1.4 on 2019-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_is_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
    ]
