# Generated by Django 2.1.4 on 2019-01-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20190108_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于非菜单权限需要选择一个可以成为菜单的权限，用户做默认展开和选中菜单', null=True, on_delete=True, related_name='parent', to='rbac.Permission', verbose_name='关联的权限'),
        ),
    ]
