# Generated by Django 2.1.4 on 2019-01-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20190109_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='URL的别名'),
        ),
    ]
