# Generated by Django 2.1.4 on 2019-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20190109_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_data',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
